language: node_js
node_js:
  - 10
  - 11
  - 12
  - 13
  - 14
sudo: false
script:
  # Run test script
  - npm run test-ci
  # Run linting
  - npm run lint
after_script:
  - |
    # Upload coverage to coveralls
    npm install --save-dev coveralls@3.1.0
    nyc report --reporter=text-lcov | coveralls
